# Generated by Django 4.2.7 on 2024-01-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_userprofile_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="author",
            field=models.CharField(default="Unknown", max_length=31),
            preserve_default=False,
        ),
    ]
